server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatroom?useSSL=false&serverTimezone=GMT
    username: root
    password: xcdrf305
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#七牛云配置
qiniu:
  accessKey: fJmemSxXgBrNfiAYeukCAuR40DQVrMCqTXv9Tztp
  secretKey: L0GNAkV7pmXNo4CNUopXgtYXvW9V6vdzqgqteitx
  bucket: iscyf-chatroom
  path: http://q2ayul341.bkt.clouddn.com
